apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - boardApi-ingress.yaml

namespace: board-api

images:
  - name: fsdp/board-api
    newName: docker.io/fsdp/board-api
    newTag: 1.0.0.prod-kind

commonLabels:
  app: board-api