server:
    port: 8000

logging:
    level:
        org:
            springframework: DEBUG

# JPA Connection Setting
spring:
    datasource:
        # Database : MariaDB
        driver-class-name: org.mariadb.jdbc.Driver
        # URL IP link to container name
        url: jdbc:mariadb://mariadb:3306/board
        # Database username
        username: root                                                               
        # Database user password
        password: 123456