apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - boardApi-deploy.yaml
  - boardApi-svc.yaml

namespace: board-api

images:
  - name: fsdp/board-api
    newName: docker.io/fsdp/board-api
    newTag: 1.0.0.prod-np

commonLabels:
  app: board-api